services:

  echoquiz-nchan:
    image: "nginx:1.29-alpine"
    container_name: "echoquiz-nchan"
    # restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.nchan
    entrypoint: ["nginx", "-g", "daemon off;"]
#    command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      #- "--providers.docker=true"
      #- "--providers.docker.exposedbydefault=false"
      #- "--entrypoints.web.address=:80"
    ports:
      - "3001:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx-echoquiz.conf:/etc/nginx/conf.d/nginx-echoquiz.conf:ro"
      - ./../web/:/var/www/html
    networks:
      - echoquiz_net
      - mariadb_net

  echoquiz-php:
    image: php:8.3-fpm
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: echoquiz-php
    volumes:
      - ./../web/:/var/www/html
    networks:
      - echoquiz_net
      - mariadb_net

networks:
  echoquiz_net:
    driver: bridge
  mariadb_net:
    external: true
